version: "3"
services:    
    nginx:
        #build:
        #    context: ./docker
        #    dockerfile: Dockerfile
        image: frontol_nginx:v0.1
        container_name: frontol_nginx    
        ports:
            - 127.0.0.1:${NGINX_PORT}:80
        #volumes:
        #    - .:/app:cached
        #    - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro,cached
        # build:
        #    context: ./php7.4-fpm
        #    dockerfile: Dockerfile-cron
        # image: php7.4-cron-sunday-m2 