#---------------------------------------------------------------------
# GitHub Action Deploy
#---------------------------------------------------------------------
name: GitHubActions-Deploy
env:
  APPLICATION_NAME    : "FrontolServiceSite"
  DEPLOY_PACKAGE_NAME : "frontol-service-ver-${{ github.sha }}"
  DEPLOY_FOLDER       : "www/frontol/releases"
  
on: 
  push:
    branches: 
      - master
      
jobs:
  build-frontol-service-site:
    name: Build
    runs-on: ubuntu-latest
      
    steps:
    - name: 01. Start build application
      run : |
        echo "01. Start build application"
        echo "DEPLOY_CURRENT_FOLDER=$(date '+%Y%m%d%H%M%S')" >> $GITHUB_ENV
        #echo "OUTPUT=output-$(date "+%Y.%m.%d-%H.%M.%S")" >> $GITHUB_ENV
    
    - name: 02. Execure few commands
      run : |        
        echo "Hello Message1"
        echo "Hello Message2"
        echo "Appication name: ${{ env.APPLICATION_NAME }}"
        echo "Deploy package name: ${{ env.DEPLOY_PACKAGE_NAME }}"
        echo "Deploy current folder: ${{ env.DEPLOY_CURRENT_FOLDER }}"        
        
    - name: 03. List current folder
      run : ls -la
   
    - name: 04. Git clone repository
      uses: actions/checkout@v2
    
    - name: 05. Install node js
      uses: actions/setup-node@v1
      with:
          node-version: '14'
          cache: 'npm'
          
    - name: 06. Install dependency
      run : npm install
      
    - name: 07. Build project
      run : gulp build
      
    - name: 08. List current folder
      run : ls -la   
      
    - name: 09. Install SSH Key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_PRIVATE_KEY }} 
        known_hosts: ${{ secrets.SSH_HOST }}
            
    - name: 10. Adding Known Hosts
      run : ssh-keyscan -p ${{ secrets.SSH_PORT }} -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
            
    #- name: 11. Deploy with rsync
    #  run : |        
    #    rsync -avz -e "ssh -p ${{ secrets.SSH_PORT }}" \
    #        --progress --verbose \
    #        --rsync-path="mkdir -p /home/${{ secrets.SSH_USER }}/${{ env.DEPLOY_FOLDER }} && rsync" \
    #        ./assets/build/ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/home/${{ secrets.SSH_USER }}/${{ env.DEPLOY_FOLDER }}/${{ env.DEPLOY_CURRENT_FOLDER }}
    
    - name: 11.0 Create symbolic link test
      run : |        
        ssh -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "echo Test01 && whoami && ls -l /home/${{ secrets.SSH_USER }}/${{ env.DEPLOY_FOLDER }}"
        ssh -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "echo Test02 && whoami && ls -l /home/${{ secrets.SSH_USER }}/${{ env.DEPLOY_FOLDER }}"
        #ssh -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "echo Test03 && whoami && ls -l /home/${{ secrets.SSH_USER }}/${{ env.DEPLOY_FOLDER }}"
        #ssh -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "echo Test04 && whoami && ls -l /home/${{ secrets.SSH_USER }}/${{ env.DEPLOY_FOLDER }}"
        #ssh -vvv -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "echo Test05 && whoami && ls -l /home/${{ secrets.SSH_USER }}/${{ env.DEPLOY_FOLDER }}"
        #ssh -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "echo Test05 && whoami && ls -l /home/${{ secrets.SSH_USER }}/${{ env.DEPLOY_FOLDER }}"           
    
    #- name: 11.1 Executing remote  command Test01
    #  uses: appleboy/ssh-action@master
    #  with:
    #    HOST:     ${{ secrets.SSH_HOST }}
    #    USERNAME: ${{ secrets.SSH_USER }}
    #    PORT:     ${{ secrets.SSH_PORT }}
    #    KEY:      ${{ secrets.SSH_PRIVATE_KEY }}
    #    script: |
    #      echo Test01
    #      whoami
    #      ls -l /home/${{ secrets.SSH_USER }}/${{ env.DEPLOY_FOLDER }}
    
    #- name: 11.2 Executing remote  command Test02
    #  uses: appleboy/ssh-action@master
    #  with:
    #    HOST:     ${{ secrets.SSH_HOST }}
    #    USERNAME: ${{ secrets.SSH_USER }}
    #    PORT:     ${{ secrets.SSH_PORT }}
    #    KEY:      ${{ secrets.SSH_PRIVATE_KEY }}
    #    script: |
    #      echo Test02
    #      whoami
    #      ls -l /home/${{ secrets.SSH_USER }}/${{ env.DEPLOY_FOLDER }}
          
    #- name: 11.3 Executing remote  command Test03
    #  uses: appleboy/ssh-action@master
    #  with:
    #    HOST:     ${{ secrets.SSH_HOST }}
    #    USERNAME: ${{ secrets.SSH_USER }}
    #    PORT:     ${{ secrets.SSH_PORT }}
    #    KEY:      ${{ secrets.SSH_PRIVATE_KEY }}
    #    script: |
    #      echo Test03
    #      whoami
    #      ls -l /home/${{ secrets.SSH_USER }}/${{ env.DEPLOY_FOLDER }}      
                        
    #- name: 12. Create symbolic link test
    #  run : |        
    #    ssh -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "echo Test01 && whoami && ls -l /home/${{ secrets.SSH_USER }}/${{ env.DEPLOY_FOLDER }}"
    #    ssh -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "echo Test02 && whoami && ls -l /home/${{ secrets.SSH_USER }}/${{ env.DEPLOY_FOLDER }}"
    #    ssh -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "echo Test03 && whoami && ls -l /home/${{ secrets.SSH_USER }}/${{ env.DEPLOY_FOLDER }}"
    #    ssh -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "echo Test04 && whoami && ls -l /home/${{ secrets.SSH_USER }}/${{ env.DEPLOY_FOLDER }}"
    #    ssh -vvv -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "echo Test05 && whoami && ls -l /home/${{ secrets.SSH_USER }}/${{ env.DEPLOY_FOLDER }}"
    #    #ssh -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "echo Test05 && whoami && ls -l /home/${{ secrets.SSH_USER }}/${{ env.DEPLOY_FOLDER }}"        
    #    #ssh -vvv -p ${{ secrets.SSH_PORT }} -i ~/.ssh/id_rsa ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "ls -l /home/${{ secrets.SSH_USER }}/${{ env.DEPLOY_FOLDER }}"
    
    - name: 11.1 Wget 1
      run : wget https://google.com
      
    - name: 11.2 Wget 2
      run : wget https://google.com  
    
    #- name: 12. Copy file via scp
    #  uses: appleboy/scp-action@master
    #  env:
    #    HOST:     ${{ secrets.SSH_HOST }}
    #    USERNAME: ${{ secrets.SSH_USER }}
    #    PORT:     ${{ secrets.SSH_PORT }}
    #    KEY:      ${{ secrets.SSH_PRIVATE_KEY }}
    #  with:
    #    source: "./assets/build/"
    #    target: "/home/${{ secrets.SSH_USER }}/${{ env.DEPLOY_FOLDER }}/${{ env.DEPLOY_CURRENT_FOLDER }}"

    #- name: 12.1 Executing remote  command
    #  uses: appleboy/ssh-action@master
    #  with:
    #    HOST:     ${{ secrets.SSH_HOST }}
    #    USERNAME: ${{ secrets.SSH_USER }}
    #    PORT:     ${{ secrets.SSH_PORT }}
    #    KEY:      ${{ secrets.SSH_PRIVATE_KEY }}
    #    script: cat /home/${{ secrets.SSH_USER }}/${{ env.DEPLOY_FOLDER }}/${{ env.DEPLOY_CURRENT_FOLDER }}/README.md
                
    - name: 13. Finish build application
      run : echo "09. Finish build application"
      

  deploy-frontol-service-site:
    name: Deploy
    needs: build-frontol-service-site
    runs-on: ubuntu-latest
    
    steps:
    - name: 01. Start deploy application
      run : |
        echo "01. Start deploy application"
        echo "DEPLOY_CURRENT_FOLDER=$(date '+%Y%m%d%H%M%S')" >> $GITHUB_ENV        
        
    - name: 09. Install SSH Key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_PRIVATE_KEY }} 
        known_hosts: ${{ secrets.SSH_HOST }}
            
    - name: 10. Adding Known Hosts
      run : ssh-keyscan -p ${{ secrets.SSH_PORT }} -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
      
    - name: 11.0 Create symbolic link test
      run : |        
        ssh -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "echo Test01 && whoami && ls -l /home/${{ secrets.SSH_USER }}/${{ env.DEPLOY_FOLDER }}"
        ssh -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "echo Test02 && whoami && ls -l /home/${{ secrets.SSH_USER }}/${{ env.DEPLOY_FOLDER }}"  
