#---------------------------------------------------------------------
# GitHub Action Deploy
#---------------------------------------------------------------------
name: GitHubActions-Deploy
env:
  APPLICATION_NAME    : "FrontolServiceSite"
  DEPLOY_PACKAGE_NAME : "frontol-service-ver-${{ github.sha }}"
  
on: 
  push:
    branches: 
      - master
      
jobs:
  build-frontol-service-site:
    runs-on: ubuntu-latest
      
    steps:
    - name: 01. Start build application
      run : echo "01. Start build application"
    
    - name: 02. Execure few commands
      run : |
        echo "Hello Message1"
        echo "Hello Message2"
        echo "Appication name: ${{ env.APPLICATION_NAME }}"
        echo "Deploy package name: ${{ env.DEPLOY_PACKAGE_NAME }}"
        
    - name: 03. List current folder
      run : ls -la
   
    - name: 04. Git clone repository
      uses: actions/checkout@v2
    
    - name: 05. Install node js
      uses: actions/setup-node@v1
      with:
          node-version: '14'
          cache: 'npm'
          
    - name: 06. Install dependency
      run : npm install
      
    - name: 07. Build project
      run : gulp build
      
    - name: 08. List current folder
      run : ls -la   
      
    - name: 09. Install SSH Key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_PRIVATE_KEY }} 
        known_hosts: ${{ secrets.SSH_HOST }}
            
    - name: 10. Adding Known Hosts
      run : ssh-keyscan -p ${{ secrets.SSH_PORT }} -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
      
    - name: 11. Deploy with rsync
      run : rsync -avz -e 'ssh -p ${{ secrets.SSH_PORT }}' --progress --verbose --relative ./assets/build/ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/home/${{ secrets.SSH_USER }}/www/frontol.chance-ltd.ru/current/
        
    - name: 19. Finish build application
      run : echo "09. Finish build application"
