#---------------------------------------------------------------------
# GitHub Action Deploy
#---------------------------------------------------------------------
name: GitHubActions-Deploy
env:
  APPLICATION_NAME    : "FrontolServiceSite"
  DEPLOY_PACKAGE_NAME : "frontol-service-ver-${{ github.sha }}"
  
on: 
  push:
    branches: 
      - master
      
jobs:
  build-frontol-service-site:
    runs-on: ubuntu-latest
      
    steps:
    - name: 01. Start build application
      run : echo "01. Start build application"
    
    - name: 02. Execure few commands
      run : |
        echo "Hello Message1"
        echo "Hello Message2"
        echo "Appication name: ${{ env.APPLICATION_NAME }}"
        echo "Deploy package name: ${{ env.DEPLOY_PACKAGE_NAME }}"
        
    - name: 03. List current folder
      run : ls -la
   
    - name: 04. Git clone repository
      uses: actions/checkout@v2
    
    - name: 05. Install node js
      uses: actions/setup-node@v1
      with:
          node-version: '14'
          
    - name: 06. Install dependency
      run : npm install
      
    - name: 07. Build project
      run : gulp
      
    - name: 08. List current folder
      run : ls -la   
        
    - name: 09. Finish build application
      run : echo "09. Finish build application"
